Bug fix
MagicAppByNK/ObjectifyXlsx pull request #7
Opened 2023-11-28 20:09 UTC by boygear

2023-11-30 01:14 UTC, axandar requested changes

2023-11-30 01:14 UTC, axandar commented on src/main/java/pl/nowekolory/objectifyxlsx/cell/CellCreator.java
> +        if(value == 0.0){
Czemu ten fix jest tylko dla typu Double? Float też nie powinien tego mieć? Inne wartości liczbowe nie potrzebują?

2023-11-30 01:14 UTC, axandar commented on src/main/java/pl/nowekolory/objectifyxlsx/cell/CellStyleCreator.java
> +    private static final String defaultDateFormat = "M.d.yy";
Zapisz dokumentację w kodzie, że jest to wewnętrzny wzór excela i nie można tego zmieniać.

2023-11-30 01:14 UTC, axandar commented on src/main/java/pl/nowekolory/objectifyxlsx/cell/CellStyleCreator.java
> +        var stringFormat = getFormat(format, DateFormatConverter.convert(Locale.getDefault(), "dd.MM.yyyy"));
Nie używajmy Locale.getDefault - taki kod jest zależny od systemu. Narzucajmy jakiś standardowy dla nas lub dla typu danych.

2023-11-30 10:33 UTC, boygear commented on src/main/java/pl/nowekolory/objectifyxlsx/cell/CellCreator.java
> +        if(value == 0.0){
Paweł chciał, żeby ujednolicić to, że jest jest 0.0 a w niektórych nic to ma być wszędzie nic. Osobiście uważam, że to nie jest dobre wsadzanie wszędzie pustych miejsc zamiast 0. Spytam jeszcze Pawła o to. Float zmienię bo to podobna sytuacja, ale swoją drogą nigdzie chyba nie używam tego typu.

2023-11-30 10:50 UTC, boygear commented on src/main/java/pl/nowekolory/objectifyxlsx/cell/CellStyleCreator.java
> +    private static final String defaultDateFormat = "M.d.yy";
Sprawdziłem to i np: d.M.yy też działa, więc zmieniłem na taki bo jest czytelniejszy. Mam wrażenie, że excel jest w stanie złapać praktycznie dowolny format zgodny ze standardami. Zostawię tam informację, że format powinien być zgodny ze standardem Excela

2023-11-30 10:51 UTC, boygear commented on src/main/java/pl/nowekolory/objectifyxlsx/cell/CellStyleCreator.java
> +        var stringFormat = getFormat(format, DateFormatConverter.convert(Locale.getDefault(), "dd.MM.yyyy"));
Zmienione na pl

2023-12-05 23:22 UTC, axandar commented on src/main/java/pl/nowekolory/objectifyxlsx/cell/CellCreator.java
> +        if(value == 0.0){
Dodaj to jako task i psytaj Pawła

2023-12-05 23:33 UTC, axandar commented on src/main/java/pl/nowekolory/objectifyxlsx/cell/CellStyleCreator.java
> +        var stringFormat = getFormat(format, DateFormatConverter.convert(Locale.getDefault(), "dd.MM.yyyy"));
Nie możemy ot tak zmienić na PL. Działa to na serwerze? 
Przy domyslnym Locale nigdy nie wiemy co będzie na serwerze wybrane jako domyślne. Przy narzuceniu "PL" nie mamy pewności że Locale PL jest zainstalowane.
en_US powinno być wszędzie wspierane, możemy takiego użyć?

2024-02-13 22:40 UTC, merged